### ISSUE TITLE
Hc11 cc1101

### ISSUE THREAD

**Issue by rmapnms** [Legion2/Somfy_Remote_Lib#13]
Hi Leroy and thanks for the great post!

I'm trying to built the same setup and I'm currently using the Hc11 cc1101 board. I'm connecting it as such;

HC11 -- ESP32
GND -- GND
VCC -- 3V
TX -- RX
RX -- TX

I've uploaded the code to the ESP32 but can't make it to work even after following the programming steps for a new Somfy remote.

Can you help?

**Comment by Legion2** [comment]
This library uses https://github.com/LSatan/SmartRC-CC1101-Driver-Lib to control the cc1101. I don't know if it supports Hc11 cc1101 and how to wire it.
